#!/usr/bin/env bash
#
# Write compose.override.yaml: one read-only collector mount per CODE_ROOT_N
# (N >= 2), targeting /host/code/rootN. CODE_ROOT_1 stays in compose.yaml.
#
# Compose auto-merges compose.override.yaml whenever it reads the default
# compose.yaml, so plain `docker compose …` picks the mounts up too.
#
# Values are read the way compose reads them: process environment first, then
# .env. The file is rewritten only when its content changes, and a
# compose.override.yaml this script did not write is never touched.
#
# Usage: scripts/installer/compose-override.sh [--check]
#   --check   exit 1 if the file is missing or stale, change nothing
#
# bash 3.2 compatible (macOS /bin/bash): no associative arrays, no mapfile.

set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"
OUT="${COMPOSE_OVERRIDE_FILE:-$ROOT_DIR/compose.override.yaml}"
MARKER="# Generated by scripts/installer/compose-override.sh — do not edit."

CHECK=false
case "${1:-}" in
  --check) CHECK=true ;;
  "") ;;
  *) echo "unknown argument: $1" >&2; exit 2 ;;
esac

die() { echo "compose-override: $*" >&2; exit 1; }

# One .env value, with a single layer of matching quotes removed.
env_file_value() {
  local line value
  [[ -f "$ENV_FILE" ]] || return 0
  line="$(grep -E "^$1=" "$ENV_FILE" | tail -1 || true)"
  [[ -n "$line" ]] || return 0
  value="${line#*=}"
  if [[ ${#value} -ge 2 ]]; then
    case "$value" in
      \"*\") value="${value:1:${#value}-2}" ;;
      \'*\') value="${value:1:${#value}-2}" ;;
    esac
  fi
  printf '%s' "$value"
}

root_value() {
  if [[ -n "${!1+x}" ]]; then
    printf '%s' "${!1}"
  else
    env_file_value "$1"
  fi
}

root_indexes() {
  {
    if [[ -f "$ENV_FILE" ]]; then
      sed -n 's/^CODE_ROOT_\([0-9][0-9]*\)=.*/\1/p' "$ENV_FILE"
    fi
    compgen -v CODE_ROOT_ | sed -n 's/^CODE_ROOT_\([0-9][0-9]*\)$/\1/p'
  } | awk '$1 >= 2' | sort -n -u
}

# Double-quoted YAML scalar, with $ doubled so compose does not interpolate it.
yaml_path() {
  local v="$1"
  v="${v//\\/\\\\}"
  v="${v//\"/\\\"}"
  v="${v//\$/\$\$}"
  printf '"%s"' "$v"
}

render() {
  local n name value count=0 body=""
  for n in $(root_indexes); do
    name="CODE_ROOT_$n"
    value="$(root_value "$name")"
    [[ -n "$value" ]] || continue
    case "$value" in
      /*) ;;
      *) die "$name must be an absolute path, got \"$value\"" ;;
    esac
    [[ "$value" != *$'\n'* ]] || die "$name contains a newline"
    # A missing source is fatal here, not later: Docker would create it as an
    # empty directory, the mount would exist, and the collector's startup
    # check would pass with nothing to read.
    [[ -d "$value" ]] || die "$name=$value is not a directory on this machine"
    body="$body      - type: bind
        source: $(yaml_path "$value")
        target: /host/code/root$n
        read_only: true
"
    count=$((count + 1))
  done

  printf '%s\n' "$MARKER"
  printf '# Source: CODE_ROOT_2… in .env. Regenerate with: make compose-override\n'
  if [[ $count -eq 0 ]]; then
    printf 'services: {}\n'
  else
    printf 'services:\n  collector:\n    volumes:\n%s' "$body"
  fi
}

if [[ -f "$OUT" ]] && ! head -1 "$OUT" | grep -qxF "$MARKER"; then
  die "$OUT exists and was not written by this script. Move it aside, or add the CODE_ROOT mounts to it by hand."
fi

content="$(render)"

if [[ -f "$OUT" ]] && [[ "$(cat "$OUT")" == "$content" ]]; then
  exit 0
fi

if [[ "$CHECK" == true ]]; then
  echo "compose-override: $OUT is missing or stale — run: make compose-override" >&2
  exit 1
fi

tmp="$(mktemp "$OUT.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
printf '%s\n' "$content" > "$tmp"
mv "$tmp" "$OUT"
trap - EXIT
echo "wrote $OUT"
